build-job:
  tags:
    - qxp-web-runner
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  tags:
    - qxp-web-runner
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
