variables:
  IMAGE_REPO: dockerhub.qingcloud.com/lowcode

stages:
  - install
  - test
  - build
  - release

cache:
  key: node_modules
  paths:
    - node_modules/

install_node_modules_go_packages:
  tags:
    - qxp-web-runner
  stage: install
  script:
    - yarn install --registry=http://r.npm.internal.yunify.com

lint_js:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - yarn run lint

integrate:
  tags:
    - qxp-web-runner
  stage: test
  script:
    - node_modules/.bin/tsc --noEmit --skipLibCheck --pretty

build_all:
  tags:
    - qxp-web-runner
  stage: build
  only:
    - tags
    - release
  script:
    - make build
    - NODE_ENV=production ./node_modules/.bin/rollup --config rollup.config.js
    - go mod tidy
    - go mod vendor
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - docker build -t "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG" -f ./deploy/Dockerfile-portal .
    - docker build -t "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG" -f ./deploy/Dockerfile-home .
    - docker build -t "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG" -f ./deploy/Dockerfile-nginx .
    - docker tag $IMAGE_REPO/qxp-web-home:$IMAGE_TAG $IMAGE_REPO/qxp-web-home:$CI_COMMIT_REF_NAME
    - docker tag $IMAGE_REPO/qxp-web-portal:$IMAGE_TAG $IMAGE_REPO/qxp-web-portal:$CI_COMMIT_REF_NAME
    - docker tag $IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG $IMAGE_REPO/qxp-web-nginx:$CI_COMMIT_REF_NAME
    - docker push "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
    - docker push "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
    - docker push "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"
    - docker push "$IMAGE_REPO/qxp-web-nginx:$CI_COMMIT_REF_NAME"
    - docker push "$IMAGE_REPO/qxp-web-portal:$CI_COMMIT_REF_NAME"
    - docker push "$IMAGE_REPO/qxp-web-home:$CI_COMMIT_REF_NAME"
    - docker rmi "$IMAGE_REPO/qxp-web-nginx:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-portal:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-home:$IMAGE_TAG"
    - docker rmi "$IMAGE_REPO/qxp-web-nginx:$CI_COMMIT_REF_NAME"
    - docker rmi "$IMAGE_REPO/qxp-web-portal:$CI_COMMIT_REF_NAME"
    - docker rmi "$IMAGE_REPO/qxp-web-home:$CI_COMMIT_REF_NAME"

deploy_alpha:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - alpha
  script:
    - ./scripts/deploy_alpha.sh

deploy_testing:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - release
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - bash -c "helm upgrade qxp-web-portal /root/quanxiang_charts_test/qxp-web-portal --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - bash -c "helm upgrade qxp-web-home /root/quanxiang_charts_test/qxp-web-home --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - bash -c "helm upgrade qxp-web-nginx /root/quanxiang_charts_test/qxp-web-nginx --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - echo "deploy testing done!"

deploy_staging:
  tags:
    - qxp-web-runner
  stage: release
  only:
    - tags
    - /^v(\d+\.)+(\d+)/
  except:
    - branches
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - bash -c "helm upgrade qxp-web-portal /root/quanxiang_charts_staging/qxp-web-portal --kubeconfig ~/.kube/config_staging --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - bash -c "helm upgrade qxp-web-home /root/quanxiang_charts_staging/qxp-web-home --kubeconfig ~/.kube/config_staging --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - bash -c "helm upgrade qxp-web-nginx /root/quanxiang_charts_staging/qxp-web-nginx --kubeconfig ~/.kube/config_staging --set image.tag=$IMAGE_TAG --set image.repo=dockerhub.qingcloud.com/lowcode -n lowcode"
    - echo "deploy staging done!"
